{% set name = "execjs" %}
{% set version = "2.8.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: c69b36c254a010d1b6c4cd9d2d33cb97d3d7fd94a2f8933da3591d20a5dad8d7

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  requires:
    - nodejs
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE
  summary: ExecJS lets you run JavaScript code from Ruby

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rails/{{ name }}

extra:
  recipe-maintainers:
    - sodre
