travis:
  secure:
    BINSTAR_TOKEN: N/3rzAjUpAD38b+Co8yT2eQp5I/Gl/sz7DpHN/Sb8EfWnDwRN3yZmLdvJYUTK6nRXWIlFsVFE2moukWZXJF+nm/TPHu/PB4VLKT4L/s9lwr6CbR995t4rtaxbjM86mrs06hdX8JBL1qbUmO917F7tL2y67hvMMHadb+ePjpN82qr+JGu9smcT8wJU9l5nTBu1aGPaaaV56eGQ7H7eELnzoYx/5G9uT7SN3D+mW8dAKDfQE9ztdGdAxrBeeaWhiRkex2vkAeb2+GUQVGjdfVk2k6k+NeNmZX7xU/SsA6Xyw61inT9LQudSFmNtGzhojqkkSy14WisyYeIk4GmrrzHHIl0CO0+8rnnJYNDMFCLeTSecjN87wdPBDvUeYzHcc5Wkzm1/YypDTOaXCJmpTIGqaduy4zwp6KkncaOpQqcdD9L7sLmv8BojSv6Ho/0OmBZKzlYTx3IE7/mpTi+y4vWQG9RH/uwIxX1IPbN0c1Okqk16q4Q74RBUl14RtJZgOpO3WPIALgb1y2AVAxLJFfEkE7O+BsI87PICZYajIUuhOfkOs0ncvUoHnMOs2pzj5EzRwxzv2meKuKcHqEZDcPhZj6UnfiRdbi03A7NgiOVAaOhcdNziguU0GRPkMp5TfM7L5W1GZDKxGSO3ZfxyjoXDHUKJabmZCmrcnP1WBzuPqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
